### ISSUE TITLE
Transfer to schurerlab shiny and mask URL as ckoi.ccs.miami.edu

### ISSUE THREAD

**Issue by sschurer** [schurerlab/DarkKinomeApp#4]
Transfer App to the schurerlab shiny domain
Please see if we can mask and actually show cki.ccs.miami.edu similar to synergyseq

**Comment by chung88** [comment]
From: Davila, Pedro Manuel <pedro@miami.edu>
Sent: Monday, September 16, 2019 12:06 PM
To: Chung, Caty Elizabeth <c.chung@med.miami.edu>; Turner, John <jpt55@med.miami.edu>
Subject: Re: cki.ccs.miami.edu 

Hi Caty, John,
I don’t think this is possible.  I tried a reverse proxy.  I also tried to embed the redirect in an iframe.
Best,
Pedro

From: "Chung, Caty Elizabeth" <c.chung@med.miami.edu>
Date: Monday, September 16, 2019 at 6:59 AM
To: Pedro Davila <pedro@miami.edu>, "Turner, John" <jpt55@med.miami.edu>
Subject: cki.ccs.miami.edu

Hi Pedro, John,
sschurer 6:54 AM is there some way to mask https://rimsk.shinyapps.io/Appkin/ with cki.ccs.miami.edu, not just redirect?
Caty

**Comment by sschurer** [comment]
Please read the issue
There are two parts:
transfer to schurerlab shiny (from rimps shiny)
mask URL
you only dismissed one

**Comment by chung88** [comment]
The issue was closed, because the steps cannot be done similar to synergyseq.  
I do not understand, why do you want to mask the URL?  
Ticket has been created:  [ccstkt #36371]

From: Chung, Caty Elizabeth
Sent: Friday, March 6, 2020 3:10 PM
To: hpc@ccs.miami.edu <hpc@ccs.miami.edu>
Cc: Khurana, Rimpi <rxk519@miami.edu>; Stephan Schurer, PhD <stephan.schurer@gmail.com>
Subject: migration of https://rimsk.shinyapps.io/Appkin/ to cki.ccs.miami.edu
 
Pedro,
The Schurer Lab is requesting to migrate https://rimsk.shinyapps.io/Appkin/ to cki.ccs.miami.edu.
Do we have space for a vm in farnsworth?
Thanks,
Caty

**Comment by Rimsk** [comment]
I have already sent the link to Pedro to redirect the link to https://schurerlab.shinyapps.io/CKIApp/
